### ISSUE TITLE
Playify doesn't handle updated playlists

### ISSUE THREAD

**Issue by haboutnnah** [krmax44/Playify-Transfer#4]
eg. I get a playlist, use playify to move it, then I change the spotify playlist. If I then open the playlist in playify again, it uses a chached version.

**Comment by krmax44** [comment]
That's true. I'm using Cloudflare on my site to cut down on traffic and improve the performance. If you don't want to wait for the cache to reset, just add a modifier query at the end (like http://example.com?already=there&dontcachethis=yesplease).

**Comment by tf2manu994** [comment]
Hi @krmax44, I tried it just now and it doesn't work:

https://open.spotify.com/user/thepopheads/playlist/46KW71EiSxRufiJktnowT8
